[workspace]

members = [
    "extension",
    "crates/t-digest",
    "crates/hyperloglog",
    "crates/udd-sketch",
    "crates/time-weighted-average",]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
debug = true
